name: Cypress Tests


on:
  push:                  # dispara quando faz push para qualquer branch  
    branches: [ main ]
  pull_request:          # dispara quando abre ou atualiza um pull request 
    branches: [ main ]   # PRs direcionados para a branch main

jobs:

  cypress-run:
    runs-on: ubuntu-latest   
    
    services:
      api:
        image: node:v22.15.02
        ports:
          - 3000:3000
        options: >-
          --health-cmd="curl --fail http://localhost:3000/health || exit 1"
          --health-interval=10s
          --health-timeout=5s
          --health-retries=5
        # Aqui você poderia rodar sua API com npm start ou outro comando



    steps:
      # 1. Baixar o código do repositório
      - name: Checkout código
        uses: actions/checkout@v3


      # 2. Configurar Node.js
      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: v22.15.02  
          

      # 3. Instalar dependências
      - name: Instalar dependências
        run: npm install
        
        
      # 4. Subir API
      - name: Subir API local
        run: npm start &
        
        
      # 5.Esperar API
      - name: Esperar API estar disponível
        run: npx wait-on http://localhost:3000/health


      # 6. Rodar testes de API
      - name: Testes de API
        run: npx cypress run --spec "cypress/e2e/**/*.cy.js"
        

      # 7. Rodar testes de Front-end
      - name: Testes de Front-end
        run: npx cypress run --spec "cypress/e2e/**/*.cy.js"
        

      # 8. Salvar relatórios de execução
      - name: Upload Mochawesome report
        uses: actions/upload-artifact@v4
        with:
          name: mochawesome-report
          path: cypress/results/


          



